### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [mikeakohn/java_grinder#31]
Hello!

I found this project from https://www.mikekohn.net/micro/riscv_fpga.php

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by mikeakohn** [comment]
All the files have "License: MIT" at the top. Do whatever you want with it, except turn it for a homework assignement, but if you do please let me know what grade you got :).

Actually, if you do something neat with it, I'd be really cool to see what you did.

**Comment by mikeakohn** [comment]
Actually, is it the RISC-V project or Java Grinder? Java Grinder is GPLv3... the RISC-V project is MIT.

**Comment by vazhnov** [comment]
At least this file doesn't have a header with license: [java/Makefile](https://github.com/mikeakohn/java_grinder/blob/master/java/Makefile).
Could you please add `LICENSE.txt` file to the root of the project? :)

**Comment by mikeakohn** [comment]
Done!

**Comment by vazhnov** [comment]
GPL v3 — amazing!
Thank you!

**Comment by mikeakohn** [comment]
No problem.. hope the project helps you. :)

**Comment by vazhnov** [comment]
> if you do please let me know what grade you got :).
> Actually, if you do something neat with it, I'd be really cool to see what you did.

I don't use this project, sorry.
It's my hobby to remind people, who shared interesting projects, to not forget to add a license (for example: to avoid a situation when multiple cool forks were created, people spend time, but all of them are not legal because of no opensource license in the original project).

Also I'm interesting in RISC-V project, but right now playing with SiFive FE310.
