### ISSUE TITLE
Unimplemented OPCODES (187) and (1)

### ISSUE THREAD

**Issue by deringenieur71** [mikeakohn/java_grinder#6]
Hi,

trying to grind a 
[Test2CPC.zip](https://github.com/mikeakohn/java_grinder/files/206954/Test2CPC.zip)

** String name = "";  **

I get "Opcode (187) 'new' unimplemented"

Trying ** String name = NULL; ** 

it states 

"Opcode (1) 'aconst_null' unimplemented"

**Comment by mikeakohn** [comment]
aconst_null is now implemented.  As stated on the Java Grinder web page, there is no support for "new" on objects.  It's something I could possibly add in the future, but for now, it's just not a feature of Java Grinder.
